### ISSUE TITLE
FSL/5.0.7

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#216] opened 2015-05-14 14:52 UTC
There's a problem with FSL/5.0.7 that's not present in FSL/5.0.6. For instance, trying to use fslview with .7 gives me the following error: 

/opt/quarantine/FSL/5.0.7/build/bin/fslview_bin: error while loading shared libraries: libmng.so.1: cannot open shared object file: No such file or directory

while .6 works just fine. This isn't pressing obviously since the older version works fine...

**Comment by josephdviviano** [comment] 2015-05-14 15:12
Hi Melissa,

Yes this is annoying -- it is because FSL conflicts with SLICER. If you module unload SLICER, does the error go away?

**Comment by mlevesque82** [comment] 2015-05-19 16:28
No, same thing happens.

**Comment by josephdviviano** [comment] 2015-05-19 16:29
If you start a new terminal with no modules loaded, and just load 5.0.7, does the error occur?

**Comment by pipitone** [comment] 2015-05-19 16:30
Yes. :-)

**Comment by mlevesque82** [comment] 2015-05-19 16:31
I concur with Jon.

**Comment by josephdviviano** [comment] 2015-05-19 16:35
Looks like an update to Ubuntu broke 5.0.7 fslview:

https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1410&L=FSL&D=0&P=357780

But we can only install libmng2.

**Comment by pipitone** [comment] 2015-05-19 16:37
The problem is this: In the FSL/5.0.6 module, fslview is being aliased
to /usr/bin/fslview (i.e. the fslview installed on all the
workstations), but in FSL/5.0.7 this isn't happening, so the fslview in
the module is being used and that particular version depends on a
library (libmng) we don't have installed on the workstations. 

I've updated the FSL/5.0.7 module with an alias. :-)  It should work
now.

**Comment by josephdviviano** [comment] 2015-05-19 16:38
This might be a solution:

https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;fa13b362.1501

In our case ln -s /usr/lib/x86_64-linux-gnu/libmng.so.2 /usr/lib/x86_64-linux-gnu/libmng.so.1

**Comment by pipitone** [comment] 2015-05-19 16:39
Alternatively, we can install libmng-dev and the quarantined fslview
will work. :-)

**Comment by pipitone** [comment] 2015-05-26 17:14
Fixed with an alias in the modulefile.

**Closed by pipitone** 2015-05-26 17:14 UTC
