### ISSUE TITLE
megasas RESETs in the backup server syslog

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#311] opened 2015-09-23 14:36 UTC
I see this intermittently and it's worrying. Drives will have warnings like these: 

```
sd 2:2:3:0: [sdd] megasas: RESET cmd=28 retries=0
megasas: [ 0]waiting for 1 commands to complete
megaraid_sas: no pending cmds after reset
megasas: reset successful
```

What I can find on the issue: 
1. [this old thread](http://lists.us.dell.com/pipermail/linux-poweredge/2006-October/027737.html) - suggests using Dell's OMSA tools to status check
2. [SCSI sense code 28](http://www.t10.org/lists/asc-num.htm#ASC_280) - suggests device isn't ready
3. A [related ZFS issue](https://github.com/zfsonlinux/zfs/issues/2752) where this occurs during heavy I/O (not unlike our nightly backup...)

I suggest we set up the OMSA tools and get a status check, as well do a full diagnostic (we're due for one anyhow as part of dell's preventative maintenance program). Failing all of that, let's get Dell on the horn.

**Comment by josephdviviano** [comment] 2016-02-19 15:52
I'm going to refocus this: 3. from the list above suggests we need to disable 'ReadAhead'. Something like `MegaCli -ldsetprop nora -lall -a0`... might work.

**Comment by josephdviviano** [comment] 2016-02-22 20:26
@pipitone I'm going to close this because the problem isn't actually a problem, as far as I can tell, and it has no clear fix.

**Closed by josephdviviano** 2016-02-22 20:26 UTC
