### ISSUE TITLE
#!/bin/bash -l no longer works

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/admin#348] opened 2015-12-02 03:28 UTC
Hi guys,

I am trying to run HCP pipeline scripts. I have changed the scripts so that they start with #!/bin/bash.

I have added:
module load freesurfer/5.3.0-HCP

To the script. Here is the error that I get:
/scratch/arash/HCP/Pipelines-3.4.0/FreeSurfer/FreeSurferPipeline.sh: line 4: module: command not found

BTW, when I run "module load freesurfer/5.3.0-HCP", freesurfer/5.3.0 is also loaded.

Cheers,
Arash

**Comment by pipitone** [comment] 2015-12-02 14:55
Okay I'll take another look at this. 

> BTW, when I run "module load freesurfer/5.3.0-HCP", freesurfer/5.3.0 is also loaded.
> 
This is expected. The HCP module only contains mris_make_surfaces. 

Jon.

**Comment by josephdviviano** [comment] 2015-12-02 15:07
Hey Jon, does this have to do with 'module' being exported? I don't thing we ever documented the cause of this error when I ran into it a few weeks back.

**Comment by pipitone** [comment] 2015-12-02 18:13
@josephdviviano No, #338 was a memory thing and has been resolved (see my last comment for the cause). 

@arash-n, how are you submitting your script? Can you reply with your submit command?

**Comment by pipitone** [comment] 2015-12-11 15:56
I'm going to close this for now, because `bash -l` does actually work. Reopen this if you are still finding this an issue and can give me a specific example.

**Closed by pipitone** 2015-12-11 15:56 UTC
