### ISSUE TITLE
VIPR_CMH_2118_01

### ISSUE THREAD

**Issue by JessDArcey** [TIGRLab/admin#1202] opened 2017-05-24 15:26 UTC
Missing SPRL scans for all 6 Activity Runs

**Comment by navonacalarco** [comment] 2017-05-24 19:20
Thanks Jess! I'll look into it and get back to your shortly. :)

**Comment by navonacalarco** [comment] 2017-05-25 16:43
@JessDArcey Ok, it turns out that the SPRL linking is correctly looking for `Ax-ViPRfMRI`.

Based on the logs, it seems that the problem is that an old, incorrectly named scan is now stymieing the run scripts (?).

So, we're correcting the naming issue and hoping this will rectify things. Leaving open until we do.

**Comment by JessDArcey** [comment] 2017-05-25 16:44
Thanks Navona!

**Comment by navonacalarco** [comment] 2017-06-06 18:46
@tomwright01 Dawn has helped looked into this problem - missing SPRLs for VIPR participants - and it seems as though the spiral linking script is crashing when adding things to the Dashboard's database, perhaps because of the multiple copies of resources (?).

Is this the case / when will this be fixed / how can we work around this?

**Comment by DESm1th** [comment] 2017-06-06 18:48
@tomwright01 to add to this, the backup stuff seems to be causing dm2-link-sprl to leave behind broken (and duplicate) links for the subjects that run through without crashing.

**Comment by tomwright01** [comment] 2017-06-06 20:29
The insert problem should be fixed by commit da72703758df1113.

Must admit I forgot about the broken links.

**Comment by navonacalarco** [comment] 2017-06-08 18:34
Thanks @DESm1th  and @tomwright01!

@JessDArcey, it looks like your SPRLs are back! Let us know if anything is amiss.

**Closed by navonacalarco** 2017-06-08 18:34 UTC
