### ISSUE TITLE
PACTMD run script error

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#676] opened 2016-08-17 15:35 UTC
We might need to run in debug mode to figure out what happened here...

> ----------------------------------------------------------------------
>  PACTMD                                            08/17/16 00:59:25
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 409, in <module>
>     main()
>   File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 184, in main
>     bl = pd.read_table(blacklist, sep='\s*', engine="python")
>   File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/pandas/io/parsers.py", line 465, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/pandas/io/parsers.py", line 251, in _read
>     return parser.read()
>   File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/pandas/io/parsers.py", line 710, in read
>     ret = self._engine.read(nrows)
>   File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/pandas/io/parsers.py", line 1558, in read
>     alldata = self._rows_to_cols(content)
>   File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/pandas/io/parsers.py", line 1933, in _rows_to_cols
>     raise ValueError(msg)
> ValueError: Expected 2 fields in line 55, saw 6

**Comment by DESm1th** [comment] 2016-08-17 15:42
The problem is that the last line of the blacklist.csv file has extra spaces in the 'reason' field.

This line:
PACTMD_CMH_3060065_01_01_PDT2_09_OblAx-T2DEfseXL             repeated due to head position

So it's parsing it as six separate columns

**Comment by edickie** [comment] 2016-08-17 15:45
Thanks Dawn!!

Do you have the write permission to fix this yourself??

**Comment by DESm1th** [comment] 2016-08-17 15:50
Yep! I completely forgot I could sudo things on this computer. It seems to parse correctly now

**Comment by edickie** [comment] 2016-08-17 16:16
Hey guys??

Maybe we should update xnat-export in datman to print a clearer error (i.e. one's that mentions this is a problem with parsing the blacklist??)

**Comment by DESm1th** [comment] 2016-08-17 16:55
I added in an error message for this and fixed a bug with how the blacklist is read. The changes have been committed locally but not pushed to TIGRLab/datman

**Closed** 2016-08-18 15:18 UTC
