### ISSUE TITLE
Check linking on basis of REDCap 'Scan Completed'

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/admin#826] opened 2016-10-28 16:57 UTC
@DESm1th I noticed that we have our first linked scan as indicated by the Scan Completed emails!

Record 27 indicates that SPINS participant `SPN01_CMH_0104_01_01` is shared with PNS as `PNS_CMH_0027`.

Let's check and make sure everything looks as it should!

**Comment by DESm1th** [comment] 2016-10-28 16:59
Hey Navona,

Thanks for letting me know! It's not being run automatically yet so I'll run it manually today and let you know if everything comes out ok.

**Comment by navonacalarco** [comment] 2016-11-08 18:33
One addition: turns out that SPN01_CMH_0104_01_01 (exam 6188) was scanned on the day there was something wrong with DTI. So, the participant was brought back in as SPN01_CMH_0104_01_02(exam 6225) to redo DTI.

Thus, data from exam 6225 will also need to be brought over to PNS_CMH_0027.

**Comment by DESm1th** [comment] 2016-11-10 19:11
Ok, it's a bit late but I've gotten everything running correctly. It's still not being run automatically but it's ready to be whenever we want to start running it regularly.

**Comment by navonacalarco** [comment] 2016-11-14 15:17
@DESm1th Not sure if this should be a separate issue or not, but the PNS QC pages (i) don't have images, and (ii) indicate every scan is repeated.

Not urgent, but when you have time, could you please take a look?

e.g.
/archive/data-2.0/PNSC/qc/PNS_CMH_0027_01/qc_PNS_CMH_0027_01.html

**Comment by josephdviviano** [comment] 2016-11-14 16:12
@navonacalarco can you just check the NIFTI data on the filesystem? Do we have 2 of every scan?

The image generation would be unrelated to the repeat scan issue.

**Comment by DESm1th** [comment] 2016-11-14 16:14
It was a bug in dm-link-project-scans.py that was causing the file extension in the links to be reversed and then slicer was crashing. I've fixed that bug and I'm running the link script now to double check that everything is working, and that the slicer crash wasnt a separate issue.

**Comment by DESm1th** [comment] 2016-11-14 18:31
Just as an update: this specific bug with the broken extensions is now fixed, but Tom's change to the config files has temporarily broken qc-report and nearly everything else so I can't regenerate the page to confirm the issue is closed. I'll check the page tomorrow (if qc-report is working again) and see if things are resolved.

**Comment by DESm1th** [comment] 2016-11-17 22:00
Ok I finally had a chance to regenerate the page. The images are all there now and the 'repeated scan' messages are because this person was one of the ones who had to come back for a second session.

**Closed by DESm1th** 2016-11-17 22:00 UTC
