### ISSUE TITLE
COGBDY dtifit folder in data-2.0

### ISSUE THREAD

**Issue by mlevesque82** [TIGRLab/admin#266] opened 2015-08-11 21:04 UTC
There are three FA files for subject 27B029 and 2 files for 27B036 in /archive/data-2.0/COGBDY/data/dtifit/. 

For 27B029:
COGBDY_CMH_27B029_01_01_DTI60-1000_08_Ax-DTI-60+5_eddy_correct_dtifit_FA.nii.gz
COGBDY_CMH_27B029_01_01_DTI60-1000_09_Ax-DTI-60+5_eddy_correct_dtifit_FA.nii.gz
COGBDY_CMH_27B029_01_01_DTI60-1000_10_Ax-DTI-60+5_eddy_correct_dtifit_FA.nii.gz

For 27B036:
COGBDY_CMH_27B036_01_01_DTI60-1000_08_Ax-DTI-60plus5_eddy_correct_dtifit_FA.nii.gz
COGBDY_CMH_27B036_01_02_DTI60-1000_08_Ax-DTI-60plus5_eddy_correct_dtifit_FA.nii.gz

Can you advise on which to use? Thanks!

**Comment by pipitone** [comment] 2015-08-11 21:28
Good find, Melissa. We're loooking into this now. :-)

**Comment by mlevesque82** [comment] 2015-08-11 21:30
Thanks!

**Comment by pipitone** [comment] 2015-08-11 21:51
For 27B029: 
Okay, we've figured it out and are in the process of fixing it. Here's
the story. 

 - Subject 27B029 has been misnamed as S7B029. :-)
 - The data currently labelled 27B029 is *actually* a duplicate of data
   from 27B016, but somehow the dicom headers have been mangled and
   share the same StudyID (3080) as the second repeat from subject
   27B029. 

So, the fix is to: 
 - Delete subject 27B029. The zip file on the MR Unit's FTP is bad also. 
 - Rename S7B029 to 27B029. 

Tonight the data will be re-exported and we'll QC it to determine which
acquisitions are keepers. :-)

For 27B036:
It looks like there was a repeat scan done, but the technotes for the
sessions don't say why: 
      /archive/data-2.0/COGBDY/data/RESOURCES/COGBDY_CMH_27B036_01_01/20150708_201107/2015_0313_AH026/Ex03542.pdf
      /archive/data-2.0/COGBDY/data/RESOURCES/COGBDY_CMH_27B036_01_02/20150708_201705/2015_0508_AH028/Technotes.pdf

Very likely only one of them is good.

**Comment by mlevesque82** [comment] 2015-08-12 14:50
Visually, COGBDY_CMH_27B036_01_02... looks better than COGBDY_CMH_27B036_01_01...

For 27B029, there are two S7B029, which I renamed in my folder. Both look fine to me, so I'll wait to see what the QC reveals.

**Comment by josephdviviano** [comment] 2016-05-02 13:43
I'm closing this... I'm not sure there is still a problem here.

**Closed by josephdviviano** 2016-05-02 13:43 UTC
Labels: data
